### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sbasyrine** [IcaroMourao/Multivariate-Time-Series-Forecasting#1]
Hello! I'm a master student and I'm working on predicting and forecasting the status of Ireland's charging stations given a time series dataset. What I need to do is to predict the status of  exactly three charging stations at a particular hour or period of time in the future (for example what would be the state of the charging station tomorrow at 8:00 am?)
If you could help me, it will mean a lot to me and I'll be so grateful.
Sincerely.

**Comment by icaromourao** [comment]
Hello @sbasyrine. Can you more specific? What is your difficulty in specific, is the theory how can you do these predictions or about technical part?

**Comment by sbasyrine** [comment]
Hi! Thanks for replying :) let's say IT'S BOTH OF THEM --'
I have no experience with time series forecasting, This project is so important to accomplish my master project. I found my self a little bit lost and I don't know from where to start.

**Comment by icaromourao** [comment]
Well, to you begin you need learn about [Neural Networks](https://machinelearningmastery.com/what-is-deep-learning/) (here is a blog link very good to learn all about Neural Networks). In this blog you will find practically everything about this area. I'm glad to be able to help you. If you have more questions you can ask it.

**Comment by sbasyrine** [comment]
Thank you for your help :)
I want to ask if your project can be used with another dataset, and what do you mean by multivariate?

**Comment by icaromourao** [comment]
Yes, my project can be used with another dataset, but you must to do some changes. For example, my data  set use 8 features, your dataset probably don’t use 8 features. Perhaps you must change the design of yours neural network according to your need too. Exists two types of time series: Univariate and multivariate. Univariate is the serie it has only one feature, multivariate it has more than one feature.

**Comment by sbasyrine** [comment]
Does this mean If I'm going to predict the status of a charging station (the status can have 5 values fully occupied/available/out of contact / out of service and partly occupied) at a particular time (for example tomorrow at 8 am) the problem in this case is Univariate ?

**Comment by icaromourao** [comment]
Not at all ‘cause you have 5 values that is 5 features, 5 observed variables then your time serie is Multivariate. However not every dataset is a time serie ‘cause it must some components (see [here](https://arxiv.org/pdf/1302.6613.pdf) on the section 2.2 Components of a Time Series)
